development:
    server:
        port: 3000
    redis:
        host: '167.114.228.208'
        port: 6379
        channel: 'total_optimized_images'

production:
    server:
        port: 3000
    redis:
        host: '167.114.228.208'
        port: 6379
        channel: 'total_optimized_images'