development:
    server:
        port: 3000
    redis:
        host: '127.0.0.1'
        port: 6379
        channel: 'total_optimized_images'

production:
    server:
        port: 3000
    redis:
        host: '127.0.0.1'
        port: 6379
        channel: 'total_optimized_images'